### ISSUE TITLE
hydra-callbacks + hydra-zen 😄 

### ISSUE THREAD

**Issue by rsokl** [paquiteau/hydra-callbacks#2]
Hello! I came across this nice project, and it inspired me to add a how-to for [how to use Hydra's callbacks in hydra-zen](https://mit-ll-responsible-ai.github.io/hydra-zen/how_to/use_callbacks.html).  I just wanted to put this on your radar, especially because it is so simple to import callbacks from `hydra_callbacks` and add them to `ZenStore` -- no need to edit a yaml file 🚀 .

**Comment by paquiteau** [comment]
Hello :smile:  Thanks for the heads up ! Feel free to mention hydra_callback in your doc (which looks awesome btw). 

I am starting to have a fair share of hydra projects (and yaml files... ), I will probalby check how I can use hydra-zen in some of them :eyes:
